name: segue-build-macos
on: workflow_call
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package Executable
        run: |
          pyinstaller --noconfirm --log-level=WARN \
            --osx-bundle-identifier="com.github.rikashore.segue" \
            -i="res/New Piskel-1.png.icns" \
            -w \
            segue/segue.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            path: dist/*