name: segue-build-linux
on: workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package Executable
        run: |
          pyinstaller --noconfirm --log-level=WARN \
            -w \
            segue/segue.py

      - name: Zip
        run: | 
          (cd dist/segue && zip -r ../segue-linux.zip .)
          ls

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: segue-linux
            path: segue-linux.zip
            overwrite: true
